Repository abhi45hacktober/Hacktoberfest2022, pull requests merged in 2022-10, with the labels that each got.

#1 Create program1.c
  program1.c
Labels: hacktoberfest-accepted

#2 Create program2.c
  program2.c
Labels: hacktoberfest-accepted

#3 Create program3.c
  program3.c
Labels: hacktoberfest-accepted

#4 Create program4.c
  program4.c
Labels: hacktoberfest-accepted

#8 Create Program8.c
  Program8.c
Labels: hacktoberfest-accepted

#7 Create Program7.c
  Program7.c
Labels: hacktoberfest-accepted

#6 Create Program6.c
  Program6.c
Labels: good first issue, hacktoberfest-accepted

#5 Create Program5.c
  Program5.c
Labels: enhancement, good first issue, hacktoberfest-accepted

#12 Updated Readme file
  README.md
Labels: hacktoberfest-accepted

#11 Added String Code Snippet
  NonRepeatingCharacter.java
Labels: hacktoberfest-accepted

#13 Updated program1.c
  program1.c
Labels: hacktoberfest-accepted

#10 Added Binary Gap code in java
  BinaryGap.java
Labels: hacktoberfest-accepted

#23 Create program15.c
  program15.c
Labels: hacktoberfest-accepted

#22 Create program14.c
  program14.c
Labels: hacktoberfest-accepted

#19 Create program11.c
  program11.c
Labels: hacktoberfest-accepted

#20 Create program12.c
  program12.c
Labels: hacktoberfest-accepted

#21 Create program13.c
  program13.c
Labels: hacktoberfest-accepted

#16 Create Code3.c
  Code3.c
Labels: hacktoberfest-accepted
